import {
  DEFAULT_HOW_TO_USE_SECTION_KEY,
  DEFAULT_NOTION_DATABASE_SECTION_KEY,
  DEFAULT_NOTION_SETTINGS_SECTION_KEY,
} from "@/constants";

export type OrderKeys =
  | typeof DEFAULT_NOTION_DATABASE_SECTION_KEY
  | typeof DEFAULT_NOTION_SETTINGS_SECTION_KEY
  | typeof DEFAULT_HOW_TO_USE_SECTION_KEY;
